name: Build BoomerangFoo and Upload Artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Download BepInEx
    - name: Download BepInEx
      run: |
        curl -L https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.2/BepInEx_win_x64_5.4.23.2.zip --output BepInEx.zip
        mkdir BepInEx
        tar -xf BepInEx.zip -C BepInEx --strip-components=1

    # Step 2: Build the Plugin
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build BoomerangFoo.dll
      run: dotnet build --configuration Release src/BoomerangFoo.csproj

    # Step 3: Copy BoomerangFoo.dll to BepInEx/plugins/
    - name: Copy BoomerangFoo.dll to BepInEx plugins folder
      run: |
        mkdir -p BepInEx/BepInEx/plugins/M
        copy bin/Release/BoomerangFoo.dll BepInEx/BepInEx/plugins/MyPlugin/

    # Step 4: Zip the BepInEx directory
    - name: Zip the BepInEx folder
      run: |
        powershell Compress-Archive -Path BepInEx\* -DestinationPath BoomerangFoo.zip

    # Step 5: Upload BoomerangFoo.zip as an artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: BoomerangFoo-Artifact
        path: BoomerangFoo.zip
